# =========================
# Logging Configuration
# =========================
logging:
  log_file: "app.log"
  log_level: "INFO"

# =========================
# Directory Configuration
# =========================
directories:
  input: "input"
  output: "output"

# =========================
# Summary Configuration
# =========================
summary:
  max_length: 2500

# =========================
# XAI Configuration
# =========================
xai:
  api_key: "${XAI_API_KEY}"
  model: "grok-beta"